language: node_js

node_js:
  - 8.1.3

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm install

after_success:
  "firebase deploy -P staging --only functions --token $TOKEN --project $PROJECT_ID"

notifications:
  email:
    on_failure: change
    on_success: change